const quizzdata = [
  {
    num: "1",
    question: "Inside which HTML element do we put the JavaScript?",
    a: "<js>",
    b: "<scripting>",
    c: "<script>",
    d: "<javascript>",
    correct: "c",
  },
  {
    num: "2",
    question:
      "What is the correct syntax for referring to an external script called xxx.js?",
    a: '<script name="xxx.js">',
    b: '<script href="xxx.js"',
    c: '<script src="xxx.js>',
    d: '<script title="xxx.js">',
    correct: "c",
  },
  {
    num: "3",
    question: 'How do you write "Hello World" in an alert box?',
    a: 'msgBox("Hello World")',
    b: 'alert("Hello World"',
    c: 'alertBox("Hello World")',
    d: 'msg("Hello World")',
    correct: "b",
  },
  {
    num: "4",
    question: "How do you create a function in JavaScript?",
    a: "function myFunction()",
    b: "function:myFunction()",
    c: "function = myFunction()",
    d: "myFunction() = ",
    correct: "a",
  },
  {
    num: "5",
    question: 'How do you call a function named "myFunction"?',
    a: "call myFunction",
    b: "myFunction()",
    c: "call function myFunction()",
    d: "myFunction.call()",
    correct: "b",
  },
  {
    num: "6",
    question: "How to write an IF statement in JavaScript?",
    a: "if ( a == 5 ) {}",
    b: "if a == 5 then:",
    c: "if i = 5",
    d: "if i == 5 then",
    correct: "a",
  },
  {
    num: "7",
    question: "How does a FOR loop start?",
    a: "for ( i = 0; i <= 5 )",
    b: "for ( i <= 5; i++)",
    c: "for (i = 0; i <= 5; i++",
    d: "for i = 1,i <= 5",
    correct: "",
  },
  {
    num: "8",
    question: "How can you add a comment in a JavaScript?",
    a: "<!-- comment -->",
    b: "#comment",
    c: "//comment",
    d: "||comment",
    correct: "c",
  },
  {
    num: "9",
    question: "Which event occurs when the user clicks on an HTML element?",
    a: "onchange",
    b: "onscroll",
    c: "onmouseover",
    d: "onclick",
    correct: "",
  },
  {
    num: "10",
    question: "How do you declare a JavaScript variable?",
    a: "variable name",
    b: "const nameli",
    c: "v score",
    d: "int 50",
    correct: "b",
  },
];
